/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/match/{nomisId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Find a learner record match for NomisID
     * @description Checks if the given NomisID has been matched to a ULN and if found returns the ULN, Given Name and Family Name
     */
    get: operations['findMatch']
    put?: never
    /**
     * Confirm a match
     * @description Confirm a match between a NomisID and a ULN
     */
    post: operations['confirmMatch']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/match/{nomisId}/unmatch': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Confirm an un-match
     * @description Confirm that a NomisID is to be un-matched
     */
    post: operations['confirmUnmatch']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/match/{nomisId}/no-match': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Confirm that a match is not possible
     * @description Confirm a no match for a NomisID
     */
    post: operations['confirmNoMatch']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/learners': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Find learners by demographic information
     * @description Find learner and ULN by demographic information
     */
    post: operations['findByDemographic']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/learner-events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Get learning events by learner ULN
     * @description Get personal learning record and learning events by ULN
     */
    post: operations['findByUln']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/subject-access-request': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Provides content for a prisoner to satisfy the needs of a subject access request on their behalf
     * @description Requires role SAR_DATA_ACCESS or additional role as specified by hmpps.sar.additionalAccessRole configuration.
     */
    get: operations['getSarContentByReference']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/match/{nomisId}/learner-events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get learning events by Nomis ID
     * @description Get personal learning record and learning events by Nomis ID
     */
    get: operations['findLearnerEventsByNomisId']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ConfirmMatchRequest: {
      matchingUln: string
      givenName: string
      familyName: string
      /** @enum {string} */
      matchType: 'No Match' | 'Exact Match' | 'Possible Match' | 'Linked Learner Match' | 'Too Many Matches'
      countOfReturnedUlns: string
    }
    ErrorResponse: {
      /** Format: int32 */
      status: number
      errorCode?: string
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    ConfirmNoMatchRequest: {
      /** @enum {string} */
      matchType: 'No Match' | 'Exact Match' | 'Possible Match' | 'Linked Learner Match' | 'Too Many Matches'
      countOfReturnedUlns: string
    }
    LearnersRequest: {
      givenName: string
      familyName: string
      dateOfBirth: string
      /** @enum {string} */
      gender: 'MALE' | 'FEMALE' | 'NOT_KNOWN' | 'NOT_SPECIFIED'
      lastKnownPostCode: string
      previousFamilyName?: string
      schoolAtAge16?: string
      placeOfBirth?: string
      emailAddress?: string
    }
    Learner: {
      createdDate?: string
      lastUpdatedDate?: string
      uln?: string
      versionNumber?: string
      masterSubstituted?: string
      title?: string
      givenName?: string
      middleOtherName?: string
      familyName?: string
      preferredGivenName?: string
      previousFamilyName?: string
      familyNameAtAge16?: string
      schoolAtAge16?: string
      lastKnownAddressLine1?: string
      lastKnownAddressLine2?: string
      lastKnownAddressTown?: string
      lastKnownAddressCountyOrCity?: string
      lastKnownPostCode?: string
      dateOfAddressCapture?: string
      dateOfBirth?: string
      placeOfBirth?: string
      gender?: string
      emailAddress?: string
      nationality?: string
      scottishCandidateNumber?: string
      abilityToShare?: string
      learnerStatus?: string
      verificationType?: string
      otherVerificationDescription?: string
      tierLevel?: string
      linkedULNs?: string
    }
    LearnersResponse: {
      searchParameters: components['schemas']['LearnersRequest']
      /** @enum {string} */
      responseType:
        | 'No Match'
        | 'Too Many Matches'
        | 'Possible Match'
        | 'Exact Match'
        | 'Linked Learner Match'
        | 'Learner opted to not share data'
        | 'Learner could not be verified'
        | ''
      mismatchedFields?: {
        [key: string]: string[]
      }
      matchedLearners?: components['schemas']['Learner'][]
    }
    LearnerEventsRequest: {
      givenName: string
      familyName: string
      uln: string
      dateOfBirth?: string
      /** @enum {string} */
      gender?: 'MALE' | 'FEMALE' | 'NOT_KNOWN' | 'NOT_SPECIFIED'
    }
    LearnerEventsResponse: {
      searchParameters: components['schemas']['LearnerEventsRequest']
      /** @enum {string} */
      responseType:
        | 'No Match'
        | 'Too Many Matches'
        | 'Possible Match'
        | 'Exact Match'
        | 'Linked Learner Match'
        | 'Learner opted to not share data'
        | 'Learner could not be verified'
        | ''
      foundUln: string
      incomingUln: string
      learnerRecord: components['schemas']['LearningEvent'][]
    }
    LearningEvent: {
      id?: string
      achievementProviderUkprn?: string
      achievementProviderName?: string
      awardingOrganisationName?: string
      qualificationType?: string
      subjectCode?: string
      achievementAwardDate?: string
      credits?: string
      source?: string
      dateLoaded?: string
      underDataChallenge?: string
      level?: string
      status?: string
      subject?: string
      grade?: string
      awardingOrganisationUkprn?: string
      collectionType?: string
      returnNumber?: string
      participationStartDate?: string
      participationEndDate?: string
      languageForAssessment?: string
    }
    Attachment: {
      /**
       * Format: int32
       * @description The number of the attachment which will match any corresponding reference in the content section
       */
      attachmentNumber: number
      /** @description The name or description of the attachment which will be included in the report */
      name: string
      /** @description The content type of the attachment */
      contentType: string
      /** @description The url to be used to download the attachment file */
      url: string
      /**
       * Format: int32
       * @description The size of the attachment file in bytes
       */
      filesize: number
      /** @description The filename of attachment file */
      filename: string
    }
    HmppsSubjectAccessRequestContent: {
      /** @description The content of the subject access request response */
      content: unknown
      /** @description The details of any attachments for the subject access request response */
      attachments?: components['schemas']['Attachment'][]
    }
    CheckMatchResponse: {
      matchedUln?: string
      givenName?: string
      familyName?: string
      /** @enum {string} */
      status: 'Found' | 'NotFound' | 'NoMatch'
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  findMatch: {
    parameters: {
      query?: never
      header: {
        'X-Username': string
      }
      path: {
        nomisId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. Found a match or no match. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CheckMatchResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden to access this endpoint */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Successful response. Match has not been attempted yet so not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CheckMatchResponse']
        }
      }
    }
  }
  confirmMatch: {
    parameters: {
      query?: never
      header: {
        'X-Username': string
      }
      path: {
        nomisId: string
      }
      cookie?: never
    }
    /** @description ULN, Given Name, Family Name, Match Type, and Count of Returned ULNs to match with the NomisID in the path */
    requestBody: {
      content: {
        'application/json': components['schemas']['ConfirmMatchRequest']
      }
    }
    responses: {
      /** @description The request was successful and the match was created. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden to access this endpoint */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description ULN is already matched */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  confirmUnmatch: {
    parameters: {
      query?: never
      header: {
        'X-Username': string
      }
      path: {
        nomisId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The request was successful and the un-match was recorded. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden to access this endpoint */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  confirmNoMatch: {
    parameters: {
      query?: never
      header: {
        'X-Username': string
      }
      path: {
        nomisId: string
      }
      cookie?: never
    }
    /** @description Match Type, and Count of Returned ULNs to match with the NomisID in the path */
    requestBody: {
      content: {
        'application/json': components['schemas']['ConfirmNoMatchRequest']
      }
    }
    responses: {
      /** @description The request was successful and the no match was recorded. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden to access this endpoint */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  findByDemographic: {
    parameters: {
      query?: never
      header: {
        'X-Username': string
      }
      path?: never
      cookie?: never
    }
    /** @description Demographic details of the learner */
    requestBody: {
      content: {
        'application/json': components['schemas']['LearnersRequest']
      }
    }
    responses: {
      /** @description The request was successful and a response was returned. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LearnersResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden to access this endpoint */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  findByUln: {
    parameters: {
      query?: never
      header: {
        'X-Username': string
      }
      path?: never
      cookie?: never
    }
    /** @description ULN and demographic details of the learner */
    requestBody: {
      content: {
        'application/json': components['schemas']['LearnerEventsRequest']
      }
    }
    responses: {
      /** @description The request was successful and a response was returned. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LearnerEventsResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden to access this endpoint */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getSarContentByReference: {
    parameters: {
      query?: {
        /** @description NOMIS Prison Reference Number */
        prn?: string
        /** @description nDelius Case Reference Number */
        crn?: string
        /** @description Optional parameter denoting minimum date of event occurrence which should be returned in the response */
        fromDate?: string
        /** @description Optional parameter denoting maximum date of event occurrence which should be returned in the response */
        toDate?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Request successfully processed - content found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HmppsSubjectAccessRequestContent']
        }
      }
      /** @description Request successfully processed - no content found */
      204: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': Record<string, never>
        }
      }
      /** @description Subject Identifier is not recognised by this service */
      209: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': Record<string, never>
        }
      }
      /** @description The client does not have authorisation to make this request */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error occurred */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  findLearnerEventsByNomisId: {
    parameters: {
      query?: never
      header: {
        'X-Username': string
      }
      path: {
        nomisId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The request was successful and a response was returned. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LearnerEventsResponse']
        }
      }
      /** @description Match not possible exception */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden to access this endpoint */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Match not found exception */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
