generic-service:
  nameOverride: hmpps-education-and-work-plan-ui

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-education-and-work-plan-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-education-and-work-plan-cert
    modsecurity_enabled: true # enable OWASP core rules. Handle any false positives by removing or tweaking rules to not block specific args or cookies as necessary.
    modsecurity_github_team: farsight-devs

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /metrics
    metricsPort: 3001

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    FRONTEND_COMPONENTS_API_FEATURE_TOGGLE_ENABLED: "true"
    PLP_PRISONER_LIST_AND_OVERVIEW_PAGES_ENABLED: "true"
    TIMELINE_PAGE_ENABLED: "false"
    NEW_CREATE_GOAL_ROUTES_ENABLED: "false"
    PRISONER_SEARCH_API_DEFAULT_PAGE_SIZE: "9999"
    PRISONER_LIST_UI_DEFAULT_PAGINATION_PAGE_SIZE: "50"
    FEEDBACK_URL: "https://eu.surveymonkey.com/r/H9CYM7B"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-education-and-work-plan-ui:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
    education-work-plan-ui-elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

  allowlist:
    groups:
      - internal
      - prisons
      - private_prisons

generic-prometheus-alerts:
  targetApplication: hmpps-education-and-work-plan-ui
