/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/ciag/induction/{offenderId}': {
    /**
     * Fetch the CIAG profile for the offender
     * @description Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
     */
    get: operations['getCIAGProfileForOffenderId']
    /**
     * Update the CIAG profile for an offender
     * @description Called once to initially create the previousWork. Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
     */
    put: operations['updateOffenderProfile']
    /**
     * Create the CIAG profile for an offender
     * @description Called once to initially create the previousWork. Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
     */
    post: operations['createOffenderProfile']
    /**
     * Delete CIAG Profile
     * @description Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
     */
    delete: operations['deleteCIAGProfileForOffenderId']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    AchievedQualification: {
      subject?: string
      grade?: string
      /** @enum {string} */
      level?:
        | 'ENTRY_LEVEL_2'
        | 'ENTRY_LEVEL_3'
        | 'LEVEL_1'
        | 'LEVEL_2'
        | 'LEVEL_3'
        | 'LEVEL_4'
        | 'LEVEL_5'
        | 'LEVEL_6'
        | 'LEVEL_7'
        | 'LEVEL_8'
    }
    CIAGProfileDTO: {
      offenderId: string
      createdBy: string
      /** Format: date-time */
      createdDateTime: string
      modifiedBy: string
      desireToWork: boolean
      /** Format: date-time */
      modifiedDateTime: string
      /** @enum {string} */
      hopingToGetWork: 'YES' | 'NO' | 'NOT_SURE'
      reasonToNotGetWorkOther?: string
      abilityToWorkOther?: string
      abilityToWork?: (
        | 'CARING_RESPONSIBILITIES'
        | 'LIMITED_BY_OFFENSE'
        | 'HEALTH_ISSUES'
        | 'NO_RIGHT_TO_WORK'
        | 'OTHER'
        | 'NONE'
      )[]
      reasonToNotGetWork?: (
        | 'LIMIT_THEIR_ABILITY'
        | 'FULL_TIME_CARER'
        | 'LACKS_CONFIDENCE_OR_MOTIVATION'
        | 'HEALTH'
        | 'RETIRED'
        | 'NO_RIGHT_TO_WORK'
        | 'OTHER'
        | 'NO_REASON'
      )[]
      workExperience?: components['schemas']['PreviousWork']
      skillsAndInterests?: components['schemas']['SkillsAndInterests']
      qualificationsAndTraining?: components['schemas']['EducationAndQualification']
      inPrisonInterests?: components['schemas']['PrisonWorkAndEducation']
      schemaVersion?: string
    }
    EducationAndQualification: {
      modifiedBy: string
      /** Format: date-time */
      modifiedDateTime: string
      /** Format: int64 */
      id?: number
      /** @enum {string} */
      educationLevel?:
        | 'PRIMARY_SCHOOL'
        | 'SECONDARY_SCHOOL_LEFT_BEFORE_TAKING_EXAMS'
        | 'SECONDARY_SCHOOL_TOOK_EXAMS'
        | 'FURTHER_EDUCATION_COLLEGE'
        | 'UNDERGRADUATE_DEGREE_AT_UNIVERSITY'
        | 'POSTGRADUATE_DEGREE_AT_UNIVERSITY'
        | 'NOT_SURE'
      qualifications?: components['schemas']['AchievedQualification'][]
      additionalTraining?: (
        | 'CSCS_CARD'
        | 'FIRST_AID_CERTIFICATE'
        | 'FOOD_HYGIENE_CERTIFICATE'
        | 'FULL_UK_DRIVING_LICENCE'
        | 'HEALTH_AND_SAFETY'
        | 'HGV_LICENCE'
        | 'MACHINERY_TICKETS'
        | 'MANUAL_HANDLING'
        | 'TRADE_COURSE'
        | 'OTHER'
        | 'NONE'
      )[]
      additionalTrainingOther?: string
    }
    PreviousWork: {
      hasWorkedBefore: boolean
      modifiedBy: string
      /** Format: date-time */
      modifiedDateTime: string
      /** Format: int64 */
      id?: number
      typeOfWorkExperience?: (
        | 'OUTDOOR'
        | 'CONSTRUCTION'
        | 'DRIVING'
        | 'BEAUTY'
        | 'HOSPITALITY'
        | 'TECHNICAL'
        | 'MANUFACTURING'
        | 'OFFICE'
        | 'RETAIL'
        | 'SPORTS'
        | 'WAREHOUSING'
        | 'WASTE_MANAGEMENT'
        | 'EDUCATION_TRAINING'
        | 'CLEANING_AND_MAINTENANCE'
        | 'OTHER'
      )[]
      typeOfWorkExperienceOther?: string
      workExperience?: components['schemas']['WorkExperience'][]
      workInterests?: components['schemas']['WorkInterests']
    }
    PrisonWorkAndEducation: {
      modifiedBy: string
      /** Format: date-time */
      modifiedDateTime: string
      /** Format: int64 */
      id?: number
      inPrisonWork?: (
        | 'CLEANING_AND_HYGIENE'
        | 'COMPUTERS_OR_DESK_BASED'
        | 'GARDENING_AND_OUTDOORS'
        | 'KITCHENS_AND_COOKING'
        | 'MAINTENANCE'
        | 'PRISON_LAUNDRY'
        | 'PRISON_LIBRARY'
        | 'TEXTILES_AND_SEWING'
        | 'WELDING_AND_METALWORK'
        | 'WOODWORK_AND_JOINERY'
        | 'OTHER'
      )[]
      inPrisonWorkOther?: string
      inPrisonEducation?: (
        | 'BARBERING_AND_HAIRDRESSING'
        | 'CATERING'
        | 'COMMUNICATION_SKILLS'
        | 'ENGLISH_LANGUAGE_SKILLS'
        | 'FORKLIFT_DRIVING'
        | 'INTERVIEW_SKILLS'
        | 'MACHINERY_TICKETS'
        | 'NUMERACY_SKILLS'
        | 'RUNNING_A_BUSINESS'
        | 'SOCIAL_AND_LIFE_SKILLS'
        | 'WELDING_AND_METALWORK'
        | 'WOODWORK_AND_JOINERY'
        | 'OTHER'
      )[]
      inPrisonEducationOther?: string
    }
    SkillsAndInterests: {
      modifiedBy: string
      /** Format: date-time */
      modifiedDateTime: string
      /** Format: int64 */
      id?: number
      skills?: (
        | 'COMMUNICATION'
        | 'POSITIVE_ATTITUDE'
        | 'RESILIENCE'
        | 'SELF_MANAGEMENT'
        | 'TEAMWORK'
        | 'THINKING_AND_PROBLEM_SOLVING'
        | 'WILLINGNESS_TO_LEARN'
        | 'OTHER'
        | 'NONE'
      )[]
      skillsOther?: string
      personalInterests?: (
        | 'COMMUNITY'
        | 'CRAFTS'
        | 'CREATIVE'
        | 'DIGITAL'
        | 'KNOWLEDGE_BASED'
        | 'MUSICAL'
        | 'OUTDOOR'
        | 'NATURE_AND_ANIMALS'
        | 'SOCIAL'
        | 'SOLO_ACTIVITIES'
        | 'SOLO_SPORTS'
        | 'TEAM_SPORTS'
        | 'WELLNESS'
        | 'OTHER'
        | 'NONE'
      )[]
      personalInterestsOther?: string
    }
    WorkExperience: {
      /** @enum {string} */
      typeOfWorkExperience?:
        | 'OUTDOOR'
        | 'CONSTRUCTION'
        | 'DRIVING'
        | 'BEAUTY'
        | 'HOSPITALITY'
        | 'TECHNICAL'
        | 'MANUFACTURING'
        | 'OFFICE'
        | 'RETAIL'
        | 'SPORTS'
        | 'WAREHOUSING'
        | 'WASTE_MANAGEMENT'
        | 'EDUCATION_TRAINING'
        | 'CLEANING_AND_MAINTENANCE'
        | 'OTHER'
      otherWork?: string
      role?: string
      details?: string
    }
    WorkInterestDetail: {
      /** @enum {string} */
      workInterest?:
        | 'OUTDOOR'
        | 'CONSTRUCTION'
        | 'DRIVING'
        | 'BEAUTY'
        | 'HOSPITALITY'
        | 'TECHNICAL'
        | 'MANUFACTURING'
        | 'OFFICE'
        | 'RETAIL'
        | 'SPORTS'
        | 'WAREHOUSING'
        | 'WASTE_MANAGEMENT'
        | 'EDUCATION_TRAINING'
        | 'CLEANING_AND_MAINTENANCE'
        | 'OTHER'
      role?: string
    }
    WorkInterests: {
      modifiedBy: string
      /** Format: date-time */
      modifiedDateTime: string
      /** Format: int64 */
      id?: number
      workInterests?: (
        | 'OUTDOOR'
        | 'CONSTRUCTION'
        | 'DRIVING'
        | 'BEAUTY'
        | 'HOSPITALITY'
        | 'TECHNICAL'
        | 'MANUFACTURING'
        | 'OFFICE'
        | 'RETAIL'
        | 'SPORTS'
        | 'WAREHOUSING'
        | 'WASTE_MANAGEMENT'
        | 'EDUCATION_TRAINING'
        | 'CLEANING_AND_MAINTENANCE'
        | 'OTHER'
      )[]
      workInterestsOther?: string
      particularJobInterests?: components['schemas']['WorkInterestDetail'][]
    }
    ErrorResponse: {
      /** Format: int32 */
      status: number
      errorCode?: string
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    CIAGProfileRequestDTO: {
      offenderId: string
      createdBy: string
      /** Format: date-time */
      createdDateTime: string
      modifiedBy: string
      desireToWork: boolean
      /** Format: date-time */
      modifiedDateTime: string
      /** @enum {string} */
      hopingToGetWork: 'YES' | 'NO' | 'NOT_SURE'
      reasonToNotGetWorkOther?: string
      abilityToWorkOther?: string
      abilityToWork?: (
        | 'CARING_RESPONSIBILITIES'
        | 'LIMITED_BY_OFFENSE'
        | 'HEALTH_ISSUES'
        | 'NO_RIGHT_TO_WORK'
        | 'OTHER'
        | 'NONE'
      )[]
      reasonToNotGetWork?: (
        | 'LIMIT_THEIR_ABILITY'
        | 'FULL_TIME_CARER'
        | 'LACKS_CONFIDENCE_OR_MOTIVATION'
        | 'HEALTH'
        | 'RETIRED'
        | 'NO_RIGHT_TO_WORK'
        | 'OTHER'
        | 'NO_REASON'
      )[]
      workExperience?: components['schemas']['PreviousWork']
      skillsAndInterests?: components['schemas']['SkillsAndInterests']
      qualificationsAndTraining?: components['schemas']['EducationAndQualification']
      inPrisonInterests?: components['schemas']['PrisonWorkAndEducation']
      schemaVersion?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type external = Record<string, never>

export interface operations {
  /**
   * Fetch the CIAG profile for the offender
   * @description Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
   */
  getCIAGProfileForOffenderId: {
    parameters: {
      path: {
        offenderId: string
      }
    }
    responses: {
      /** @description CIAG profile is returned */
      200: {
        content: {
          'application/json': components['schemas']['CIAGProfileDTO']
        }
      }
      /** @description Invalid Parameters have been passed */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': string
        }
      }
      /** @description Incorrect permissions to access this endpoint */
      403: {
        content: {
          'application/json': string
        }
      }
      /** @description Resource not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Update the CIAG profile for an offender
   * @description Called once to initially create the previousWork. Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
   */
  updateOffenderProfile: {
    parameters: {
      path: {
        offenderId: string
      }
    }
    requestBody: {
      content: {
        'application/json': {
          requestDTO?: components['schemas']['CIAGProfileRequestDTO']
          oauth2User?: string
        }
      }
    }
    responses: {
      /** @description CIAG profile update */
      200: {
        content: {
          'application/json': components['schemas']['CIAGProfileDTO']
        }
      }
      /** @description Invalid Parameters have been passed */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to access this endpoint */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Resource not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Create the CIAG profile for an offender
   * @description Called once to initially create the previousWork. Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
   */
  createOffenderProfile: {
    parameters: {
      path: {
        offenderId: string
      }
    }
    requestBody: {
      content: {
        'application/json': {
          requestDTO?: components['schemas']['CIAGProfileRequestDTO']
          oauth2User?: string
        }
      }
    }
    responses: {
      /** @description CIAG profile created */
      200: {
        content: {
          'application/json': components['schemas']['CIAGProfileDTO']
        }
      }
      /** @description Invalid Parameters have been passed */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to access this endpoint */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Resource not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Delete CIAG Profile
   * @description Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
   */
  deleteCIAGProfileForOffenderId: {
    parameters: {
      path: {
        offenderId: string
      }
    }
    responses: {
      /** @description Successfully deleted the ,CIAG profile */
      200: {
        content: {
          'application/json': components['schemas']['CIAGProfileDTO']
        }
      }
      /** @description Invalid Parameters have been passed */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': string
        }
      }
      /** @description Incorrect permissions to access this endpoint */
      403: {
        content: {
          'application/json': string
        }
      }
      /** @description Resource not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
