/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/ciag/induction/{offenderId}': {
    /**
     * Fetch the CIAG profile for the offender
     * @description Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
     */
    get: operations['getCIAGProfileForOffenderId']
    /**
     * Update the CIAG profile for an offender
     * @description Called once to initially create the previousWork. Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
     */
    put: operations['updateOffenderProfile']
    /**
     * Create the CIAG profile for an offender
     * @description Called once to initially create the previousWork. Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
     */
    post: operations['createOffenderProfile']
    /**
     * Delete CIAG Profile
     * @description Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
     */
    delete: operations['deleteCIAGProfileForOffenderId']
  }
  '/ciag/induction/list': {
    /**
     * Fetch the CIAG profile for the given offender ids
     * @description Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
     */
    post: operations['getAllCIAGProfileForGivenOffenderIds']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    /** @description This is the qualification list of the inmate. */
    AchievedQualification: {
      /**
       * @description This is the level of  the subject the inmate has chosen.
       * @enum {string}
       */
      subject?:
        | 'ENTRY_LEVEL_2'
        | 'ENTRY_LEVEL_3'
        | 'LEVEL_1'
        | 'LEVEL_2'
        | 'LEVEL_3'
        | 'LEVEL_4'
        | 'LEVEL_5'
        | 'LEVEL_6'
        | 'LEVEL_7'
        | 'LEVEL_8'
    }
    CIAGProfileDTO: {
      /** @description This is the ID of the inmate */
      offenderId: string
      /** @description This is the prision ID of the inmate */
      prisonId?: string
      /** @description This is the prision Name of the inmate */
      prisonName?: string
      /** @description This is the person who creates the Induction.Even though it is passed from front end it wil be automatically set to the right value at the time of record creation */
      createdBy: string
      /**
       * Format: date-time
       * @description This is the creation date and time of Induction record .Even though it is passed from front end it wil be automatically set to the right value at the time of record creation
       */
      createdDateTime: string
      /** @description This is the person who modifies the Induction.Even though it is passed from front end it wil be automatically set to the right value at the time of record modification */
      modifiedBy: string
      /**
       * Format: date-time
       * @description This is the modified date and time of Induction record .Even though it is passed from front end it wil be automatically set to the right value at the time of record modification
       */
      modifiedDateTime: string
      /** @description Whether the inmate wants to work or not */
      desireToWork: boolean
      /**
       * @description Whether the inmate hopes to get work
       * @enum {string}
       */
      hopingToGetWork: 'YES' | 'NO' | 'NOT_SURE'
      /** @description This is the reason that is given when the inmate do not want to work .This field is mandatory when  "reasonToNotGetWork" has a Value set to "OTHER" */
      reasonToNotGetWorkOther?: string
      /** @description This is the factor affecting work which is peculiar to this inmate  .This field is mandatory when  "abilityToWork" has a Value set to "OTHER" */
      abilityToWorkOther?: string
      /** @description This is the factors affecting work to this inmate . */
      abilityToWork?: (
        | 'CARING_RESPONSIBILITIES'
        | 'LIMITED_BY_OFFENSE'
        | 'HEALTH_ISSUES'
        | 'NO_RIGHT_TO_WORK'
        | 'OTHER'
        | 'NONE'
      )[]
      /** @description This is the reasons for the inmate not to get work. */
      reasonToNotGetWork?: (
        | 'LIMIT_THEIR_ABILITY'
        | 'FULL_TIME_CARER'
        | 'LACKS_CONFIDENCE_OR_MOTIVATION'
        | 'HEALTH'
        | 'RETIRED'
        | 'NO_RIGHT_TO_WORK'
        | 'NOT_SURE'
        | 'OTHER'
        | 'NO_REASON'
      )[]
      workExperience?: components['schemas']['PreviousWork']
      skillsAndInterests?: components['schemas']['SkillsAndInterests']
      qualificationsAndTraining?: components['schemas']['EducationAndQualification']
      inPrisonInterests?: components['schemas']['PrisonWorkAndEducation']
      /** @description This is the schema version used */
      schemaVersion?: string
    }
    /** @description This is the qualification and training achived in the prison by the inmate. */
    EducationAndQualification: {
      /** @description This is the person who modifies the Induction.Even though it is passed from front end it wil be automatically set to the right value at the time of record modification */
      modifiedBy: string
      /**
       * Format: date-time
       * @description This is the modified date and time of Induction record .Even though it is passed from front end it wil be automatically set to the right value at the time of record modification
       */
      modifiedDateTime: string
      /** Format: int64 */
      id?: number
      /**
       * @description This is the Highest education level of the inmate.
       * @enum {string}
       */
      educationLevel?:
        | 'PRIMARY_SCHOOL'
        | 'SECONDARY_SCHOOL_LEFT_BEFORE_TAKING_EXAMS'
        | 'SECONDARY_SCHOOL_TOOK_EXAMS'
        | 'FURTHER_EDUCATION_COLLEGE'
        | 'UNDERGRADUATE_DEGREE_AT_UNIVERSITY'
        | 'POSTGRADUATE_DEGREE_AT_UNIVERSITY'
        | 'NOT_SURE'
      /** @description This is the qualification list of the inmate. */
      qualifications?: components['schemas']['AchievedQualification'][]
      /** @description This is the additional training list of the inmate. */
      additionalTraining?: (
        | 'CSCS_CARD'
        | 'FIRST_AID_CERTIFICATE'
        | 'FOOD_HYGIENE_CERTIFICATE'
        | 'FULL_UK_DRIVING_LICENCE'
        | 'HEALTH_AND_SAFETY'
        | 'HGV_LICENCE'
        | 'MACHINERY_TICKETS'
        | 'MANUAL_HANDLING'
        | 'TRADE_COURSE'
        | 'OTHER'
        | 'NONE'
      )[]
      /** @description This is the additional which is peculiar to this inmate  .This field is mandatory when  "additionalTraining" has a Value set to "OTHER" */
      additionalTrainingOther?: string
    }
    /** @description This is the previous experience of the inmate. */
    PreviousWork: {
      hasWorkedBefore: boolean
      /** @description This is the person who modifies the Induction.Even though it is passed from front end it wil be automatically set to the right value at the time of record modification */
      modifiedBy: string
      /**
       * Format: date-time
       * @description This is the modified date and time of Induction record .Even though it is passed from front end it wil be automatically set to the right value at the time of record modification
       */
      modifiedDateTime: string
      /** Format: int64 */
      id?: number
      /** @description This is the work experience list of the inmate. */
      typeOfWorkExperience?: (
        | 'OUTDOOR'
        | 'CONSTRUCTION'
        | 'DRIVING'
        | 'BEAUTY'
        | 'HOSPITALITY'
        | 'TECHNICAL'
        | 'MANUFACTURING'
        | 'OFFICE'
        | 'RETAIL'
        | 'SPORTS'
        | 'WAREHOUSING'
        | 'WASTE_MANAGEMENT'
        | 'EDUCATION_TRAINING'
        | 'CLEANING_AND_MAINTENANCE'
        | 'OTHER'
      )[]
      /** @description This is the work experience which is peculiar to this inmate  .This field is mandatory when  "typeOfWorkExperience" has a Value set to "OTHER" */
      typeOfWorkExperienceOther?: string
      /** @description This is the list of work experience details of the inmate. */
      workExperience?: components['schemas']['WorkExperience'][]
      workInterests?: components['schemas']['WorkInterests']
    }
    /** @description This is the work and training the inmate.wants to receive in prison */
    PrisonWorkAndEducation: {
      /** @description This is the person who modifies the Induction.Even though it is passed from front end it wil be automatically set to the right value at the time of record modification */
      modifiedBy: string
      /**
       * Format: date-time
       * @description This is the modified date and time of Induction record .Even though it is passed from front end it wil be automatically set to the right value at the time of record modification
       */
      modifiedDateTime: string
      /** Format: int64 */
      id?: number
      /** @description This is the prison work list of the inmate. */
      inPrisonWork?: (
        | 'CLEANING_AND_HYGIENE'
        | 'COMPUTERS_OR_DESK_BASED'
        | 'GARDENING_AND_OUTDOORS'
        | 'KITCHENS_AND_COOKING'
        | 'MAINTENANCE'
        | 'PRISON_LAUNDRY'
        | 'PRISON_LIBRARY'
        | 'TEXTILES_AND_SEWING'
        | 'WELDING_AND_METALWORK'
        | 'WOODWORK_AND_JOINERY'
        | 'OTHER'
      )[]
      /** @description This is the prison work which is peculiar to this inmate  .This field is mandatory when  "inPrisonWork" has a Value set to "OTHER" */
      inPrisonWorkOther?: string
      /** @description This is the prison education list of the inmate. */
      inPrisonEducation?: (
        | 'BARBERING_AND_HAIRDRESSING'
        | 'CATERING'
        | 'COMMUNICATION_SKILLS'
        | 'ENGLISH_LANGUAGE_SKILLS'
        | 'FORKLIFT_DRIVING'
        | 'INTERVIEW_SKILLS'
        | 'MACHINERY_TICKETS'
        | 'NUMERACY_SKILLS'
        | 'RUNNING_A_BUSINESS'
        | 'SOCIAL_AND_LIFE_SKILLS'
        | 'WELDING_AND_METALWORK'
        | 'WOODWORK_AND_JOINERY'
        | 'OTHER'
      )[]
      /** @description This is the prison education which is peculiar to this inmate  .This field is mandatory when  "inPrisonEducation" has a Value set to "OTHER" */
      inPrisonEducationOther?: string
    }
    /** @description This is the  skills and interests of the inmate. */
    SkillsAndInterests: {
      /** @description This is the person who modifies the Induction.Even though it is passed from front end it wil be automatically set to the right value at the time of record modification */
      modifiedBy: string
      /**
       * Format: date-time
       * @description This is the modified date and time of Induction record .Even though it is passed from front end it wil be automatically set to the right value at the time of record modification
       */
      modifiedDateTime: string
      /** Format: int64 */
      id?: number
      /** @description This is the skill list of the inmate. */
      skills?: (
        | 'COMMUNICATION'
        | 'POSITIVE_ATTITUDE'
        | 'RESILIENCE'
        | 'SELF_MANAGEMENT'
        | 'TEAMWORK'
        | 'THINKING_AND_PROBLEM_SOLVING'
        | 'WILLINGNESS_TO_LEARN'
        | 'OTHER'
        | 'NONE'
      )[]
      /** @description This is the skill which is peculiar to this inmate  .This field is mandatory when  "skills" has a Value set to "OTHER" */
      skillsOther?: string
      /** @description This is the interests list of the inmate. */
      personalInterests?: (
        | 'COMMUNITY'
        | 'CRAFTS'
        | 'CREATIVE'
        | 'DIGITAL'
        | 'KNOWLEDGE_BASED'
        | 'MUSICAL'
        | 'OUTDOOR'
        | 'NATURE_AND_ANIMALS'
        | 'SOCIAL'
        | 'SOLO_ACTIVITIES'
        | 'SOLO_SPORTS'
        | 'TEAM_SPORTS'
        | 'WELLNESS'
        | 'OTHER'
        | 'NONE'
      )[]
      /** @description This is the work interest which is peculiar to this inmate  .This field is mandatory when  "personalInterests" has a Value set to "OTHER" */
      personalInterestsOther?: string
    }
    /** @description This is the list of work experience details of the inmate. */
    WorkExperience: {
      /**
       * @description This is the experience of the inmate, being detailed.
       * @enum {string}
       */
      typeOfWorkExperience:
        | 'OUTDOOR'
        | 'CONSTRUCTION'
        | 'DRIVING'
        | 'BEAUTY'
        | 'HOSPITALITY'
        | 'TECHNICAL'
        | 'MANUFACTURING'
        | 'OFFICE'
        | 'RETAIL'
        | 'SPORTS'
        | 'WAREHOUSING'
        | 'WASTE_MANAGEMENT'
        | 'EDUCATION_TRAINING'
        | 'CLEANING_AND_MAINTENANCE'
        | 'OTHER'
      /** @description This is the experience of the inmate, being detailed, which is not listed in typeOfWorkExperience Enum */
      otherWork?: string
      /** @description This is the role  of the inmate, in the work ,being detailed */
      role?: string
      /** @description This is the detail of the work */
      details?: string
    }
    /** @description This is the list of detailed interests of the inmate. */
    WorkInterestDetail: {
      /**
       * @description This is the interest of the inmate, being detailed.
       * @enum {string}
       */
      workInterest:
        | 'OUTDOOR'
        | 'CONSTRUCTION'
        | 'DRIVING'
        | 'BEAUTY'
        | 'HOSPITALITY'
        | 'TECHNICAL'
        | 'MANUFACTURING'
        | 'OFFICE'
        | 'RETAIL'
        | 'SPORTS'
        | 'WAREHOUSING'
        | 'WASTE_MANAGEMENT'
        | 'EDUCATION_TRAINING'
        | 'CLEANING_AND_MAINTENANCE'
        | 'OTHER'
      /** @description This is the role of the inmate for the given work interest. */
      role: string
    }
    /** @description This is the work interests of the inmate. */
    WorkInterests: {
      /** @description This is the person who modifies the Induction.Even though it is passed from front end it wil be automatically set to the right value at the time of record modification */
      modifiedBy: string
      /**
       * Format: date-time
       * @description This is the modified date and time of Induction record .Even though it is passed from front end it wil be automatically set to the right value at the time of record modification
       */
      modifiedDateTime: string
      /** Format: int64 */
      id?: number
      /** @description This is the list of interests of the inmate. */
      workInterests: (
        | 'OUTDOOR'
        | 'CONSTRUCTION'
        | 'DRIVING'
        | 'BEAUTY'
        | 'HOSPITALITY'
        | 'TECHNICAL'
        | 'MANUFACTURING'
        | 'OFFICE'
        | 'RETAIL'
        | 'SPORTS'
        | 'WAREHOUSING'
        | 'WASTE_MANAGEMENT'
        | 'EDUCATION_TRAINING'
        | 'CLEANING_AND_MAINTENANCE'
        | 'OTHER'
      )[]
      /** @description This is the work interest which is peculiar to this inmate  .This field is mandatory when  "workInterests" has a Value set to "OTHER" */
      workInterestsOther?: string
      /** @description This is the list of detailed interests of the inmate. */
      particularJobInterests?: components['schemas']['WorkInterestDetail'][]
    }
    ErrorResponse: {
      /** Format: int32 */
      status: number
      errorCode?: string
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    CIAGProfileRequestDTO: {
      /** @description This is the ID of the inmate */
      offenderId: string
      /** @description This is the prision ID of the inmate */
      prisonId?: string
      /** @description This is the prision Name of the inmate */
      prisonName?: string
      /** @description This is the person who creates the Induction.Even though it is passed from front end it wil be automatically set to the right value at the time of record creation */
      createdBy: string
      /**
       * Format: date-time
       * @description This is the creation date and time of Induction record .Even though it is passed from front end it wil be automatically set to the right value at the time of record creation
       */
      createdDateTime: string
      /** @description This is the person who modifies the Induction.Even though it is passed from front end it wil be automatically set to the right value at the time of record modification */
      modifiedBy: string
      /**
       * Format: date-time
       * @description This is the modified date and time of Induction record .Even though it is passed from front end it wil be automatically set to the right value at the time of record modification
       */
      modifiedDateTime: string
      /** @description Whether the inmate wants to work or not */
      desireToWork: boolean
      /**
       * @description Whether the inmate hopes to get work
       * @enum {string}
       */
      hopingToGetWork: 'YES' | 'NO' | 'NOT_SURE'
      /** @description This is the reason that is given when the inmate do not want to work .This field is mandatory when  "reasonToNotGetWork" has a Value set to "OTHER" */
      reasonToNotGetWorkOther?: string
      /** @description This is the factor affecting work which is peculiar to this inmate  .This field is mandatory when  "abilityToWork" has a Value set to "OTHER" */
      abilityToWorkOther?: string
      /** @description This is the factors affecting work to this inmate . */
      abilityToWork?: (
        | 'CARING_RESPONSIBILITIES'
        | 'LIMITED_BY_OFFENSE'
        | 'HEALTH_ISSUES'
        | 'NO_RIGHT_TO_WORK'
        | 'OTHER'
        | 'NONE'
      )[]
      /** @description This is the reasons for the inmate not to get work. */
      reasonToNotGetWork?: (
        | 'LIMIT_THEIR_ABILITY'
        | 'FULL_TIME_CARER'
        | 'LACKS_CONFIDENCE_OR_MOTIVATION'
        | 'HEALTH'
        | 'RETIRED'
        | 'NO_RIGHT_TO_WORK'
        | 'NOT_SURE'
        | 'OTHER'
        | 'NO_REASON'
      )[]
      workExperience?: components['schemas']['PreviousWork']
      skillsAndInterests?: components['schemas']['SkillsAndInterests']
      qualificationsAndTraining?: components['schemas']['EducationAndQualification']
      inPrisonInterests?: components['schemas']['PrisonWorkAndEducation']
      /** @description This is the schema version used */
      schemaVersion?: string
    }
    CIAGProfileListDTO: {
      /** @description This is the List of inductions for inmates */
      ciagProfileList?: components['schemas']['CIAGProfileDTO'][]
    }
    CIAGProfileOffenderIdListRequestDTO: {
      /** @description This is the ID list of the inmates */
      offenderIds: string[]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type external = Record<string, never>

export interface operations {
  /**
   * Fetch the CIAG profile for the offender
   * @description Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
   */
  getCIAGProfileForOffenderId: {
    parameters: {
      path: {
        offenderId: string
      }
    }
    responses: {
      /** @description CIAG profile is returned */
      200: {
        content: {
          'application/json': components['schemas']['CIAGProfileDTO']
        }
      }
      /** @description Invalid Parameters have been passed */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': string
        }
      }
      /** @description Incorrect permissions to access this endpoint */
      403: {
        content: {
          'application/json': string
        }
      }
      /** @description Resource not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Update the CIAG profile for an offender
   * @description Called once to initially create the previousWork. Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
   */
  updateOffenderProfile: {
    parameters: {
      path: {
        offenderId: string
      }
    }
    requestBody: {
      content: {
        'application/json': {
          requestDTO?: components['schemas']['CIAGProfileRequestDTO']
          oauth2User?: string
        }
      }
    }
    responses: {
      /** @description CIAG profile update */
      200: {
        content: {
          'application/json': components['schemas']['CIAGProfileDTO']
        }
      }
      /** @description Invalid Parameters have been passed */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to access this endpoint */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Resource not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Create the CIAG profile for an offender
   * @description Called once to initially create the previousWork. Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
   */
  createOffenderProfile: {
    parameters: {
      path: {
        offenderId: string
      }
    }
    requestBody: {
      content: {
        'application/json': {
          requestDTO?: components['schemas']['CIAGProfileRequestDTO']
          oauth2User?: string
        }
      }
    }
    responses: {
      /** @description CIAG profile created */
      200: {
        content: {
          'application/json': components['schemas']['CIAGProfileDTO']
        }
      }
      /** @description Invalid Parameters have been passed */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to access this endpoint */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Resource not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Delete CIAG Profile
   * @description Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
   */
  deleteCIAGProfileForOffenderId: {
    parameters: {
      path: {
        offenderId: string
      }
    }
    responses: {
      /** @description Successfully deleted the ,CIAG profile */
      200: {
        content: {
          'application/json': components['schemas']['CIAGProfileDTO']
        }
      }
      /** @description Invalid Parameters have been passed */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': string
        }
      }
      /** @description Incorrect permissions to access this endpoint */
      403: {
        content: {
          'application/json': string
        }
      }
      /** @description Resource not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * Fetch the CIAG profile for the given offender ids
   * @description Currently requires role <b>ROLE_VIEW_PRISONER_DATA</b>
   */
  getAllCIAGProfileForGivenOffenderIds: {
    requestBody: {
      content: {
        'application/json': components['schemas']['CIAGProfileOffenderIdListRequestDTO']
      }
    }
    responses: {
      /** @description CIAG profile list is returned */
      200: {
        content: {
          'application/json': components['schemas']['CIAGProfileListDTO']
        }
      }
      /** @description Invalid Parameters have been passed */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': string
        }
      }
      /** @description Incorrect permissions to access this endpoint */
      403: {
        content: {
          'application/json': string
        }
      }
    }
  }
}
