// Wiremock Stubs for HMPPS Learner Records API, Match Learner Events endpoints

import { SuperAgentRequest } from 'superagent'
import { stubFor } from '../wiremock'

const stubMatchLearnerEvents = (prisonNumber = 'G6115VJ'): SuperAgentRequest =>
  stubFor({
    request: {
      method: 'GET',
      urlPattern: `/match/${prisonNumber}/learner-events`,
    },
    response: {
      status: 200,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: {
        searchParameters: {
          givenName: 'Darcie',
          familyName: 'Tucker',
          uln: '1026893096',
        },
        responseType: 'Exact Match',
        foundUln: '1026893096',
        incomingUln: '1026893096',
        learnerRecord: [
          {
            id: '190',
            achievementProviderUkprn: '10030488',
            achievementProviderName: 'LUTON PENTECOSTAL CHURCH',
            awardingOrganisationName: 'Assessment and Qualifications Alliance',
            qualificationType: 'GCE A level',
            subjectCode: '10001153',
            achievementAwardDate: '2010-07-01',
            credits: '0',
            source: 'NPD',
            dateLoaded: '2012-05-30 17:28:02',
            underDataChallenge: 'N',
            level: '',
            status: 'F',
            subject: 'AQA Advanced GCE in Information and Communication Technology',
            grade: 'E',
            awardingOrganisationUkprn: '100062',
            collectionType: 'A',
            returnNumber: '01',
            participationStartDate: '',
            participationEndDate: '',
          },
          {
            id: '191',
            achievementProviderUkprn: '10030488',
            achievementProviderName: 'LUTON PENTECOSTAL CHURCH',
            awardingOrganisationName: 'Oxford,Cambridge and RSA Examinations',
            qualificationType: 'GCE A level',
            subjectCode: '5002596X',
            achievementAwardDate: '2010-07-01',
            credits: '0',
            source: 'NPD',
            dateLoaded: '2012-05-30 17:28:02',
            underDataChallenge: 'N',
            level: '',
            status: 'F',
            subject: 'OCR Level 3 Advanced GCE in Classics',
            grade: 'A',
            awardingOrganisationUkprn: '100061',
            collectionType: 'A',
            returnNumber: '01',
            participationStartDate: '',
            participationEndDate: '',
          },
          {
            id: '192',
            achievementProviderUkprn: '10032743',
            achievementProviderName: 'PRIORSLEE PRIMARY SCHOOL ACADEMY TRUST',
            awardingOrganisationName: 'Welsh Joint Education Committee',
            qualificationType: 'GCE A level',
            subjectCode: '50026045',
            achievementAwardDate: '2010-07-01',
            credits: '0',
            source: 'NPD',
            dateLoaded: '2012-05-30 17:28:02',
            underDataChallenge: 'N',
            level: '',
            status: 'F',
            subject: 'WJEC Level 3 Advanced GCE in Design and Technology',
            grade: 'A',
            awardingOrganisationUkprn: '100040',
            collectionType: 'A',
            returnNumber: '01',
            participationStartDate: '',
            participationEndDate: '',
          },
          {
            id: '193',
            achievementProviderUkprn: '10033421',
            achievementProviderName: 'VALLEY PARK SCHOOL',
            awardingOrganisationName: 'EDEXCEL Foundation',
            qualificationType: 'BTEC National Certificate',
            subjectCode: '50016386',
            achievementAwardDate: '2011-07-01',
            credits: '0',
            source: 'NPD',
            dateLoaded: '2012-05-30 17:28:02',
            underDataChallenge: 'N',
            level: '',
            status: 'F',
            subject: 'EDEXCEL Level 3 BTEC National Certificate in Media Production',
            grade: 'MP',
            awardingOrganisationUkprn: '100060',
            collectionType: 'A',
            returnNumber: '01',
            participationStartDate: '',
            participationEndDate: '',
          },
          {
            id: '194',
            achievementProviderUkprn: '10033421',
            achievementProviderName: 'VALLEY PARK SCHOOL',
            awardingOrganisationName: 'EDEXCEL Foundation',
            qualificationType: 'BTEC National Award',
            subjectCode: '50016416',
            achievementAwardDate: '2010-07-01',
            credits: '0',
            source: 'NPD',
            dateLoaded: '2012-05-30 17:28:02',
            underDataChallenge: 'N',
            level: '',
            status: 'F',
            subject: 'EDEXCEL Level 3 BTEC National Award in Media Production',
            grade: 'P',
            awardingOrganisationUkprn: '100060',
            collectionType: 'A',
            returnNumber: '01',
            participationStartDate: '',
            participationEndDate: '',
          },
          {
            id: '195',
            achievementProviderUkprn: '10033421',
            achievementProviderName: 'VALLEY PARK SCHOOL',
            awardingOrganisationName: 'EDEXCEL Foundation',
            qualificationType: 'VRQ Level 3',
            subjectCode: '50069202',
            achievementAwardDate: '2011-07-01',
            credits: '0',
            source: 'NPD',
            dateLoaded: '2012-05-30 17:28:02',
            underDataChallenge: 'N',
            level: '',
            status: 'F',
            subject: 'EDEXCEL BTEC Level 3 Certificate in Performing Arts (QCF)',
            grade: 'A*',
            awardingOrganisationUkprn: '100060',
            collectionType: 'A',
            returnNumber: '01',
            participationStartDate: '',
            participationEndDate: '',
          },
          {
            id: '38075413',
            achievementProviderUkprn: '',
            achievementProviderName: '',
            awardingOrganisationName: 'Cambridge International Education',
            qualificationType: 'GCE A Level',
            subjectCode: '100/3432/8',
            achievementAwardDate: '2014-10-27',
            credits: '0',
            source: 'AO',
            dateLoaded: '2014-11-26 10:11:50',
            underDataChallenge: 'N',
            level: 'Level 3',
            status: 'F',
            subject: 'CCEA Advanced GCE in Mathematics',
            grade: 'Pass',
            awardingOrganisationUkprn: 'TEST0045',
            languageForAssessment: 'English',
          },
          {
            id: '38071204',
            achievementProviderUkprn: '',
            achievementProviderName: '',
            awardingOrganisationName: 'Cambridge International Education',
            qualificationType: 'GCE AS Level',
            subjectCode: '500/7690/5',
            achievementAwardDate: '2014-10-27',
            credits: '0',
            source: 'AO',
            dateLoaded: '2014-11-26 09:30:21',
            underDataChallenge: 'N',
            level: 'Level 3',
            status: 'F',
            subject: 'AQA Level 3 Advanced Subsidiary GCE in Anthropology',
            grade: 'Pass',
            awardingOrganisationUkprn: 'TEST0045',
            languageForAssessment: 'English',
          },
          {
            id: '43345743',
            achievementProviderUkprn: '',
            achievementProviderName: '',
            awardingOrganisationName: 'Cambridge International Education',
            qualificationType: 'GCE A Level',
            subjectCode: '500/2596/X',
            achievementAwardDate: '2010-07-01',
            credits: '0',
            source: 'AO',
            dateLoaded: '2016-02-03 16:04:44',
            underDataChallenge: 'Y',
            level: 'Level 3',
            status: 'F',
            subject: 'OCR Level 3 Advanced GCE in Classics',
            grade: 'A',
            awardingOrganisationUkprn: 'TEST0045',
            languageForAssessment: 'English',
          },
        ],
      },
    },
  })

const stubMatchLearnerEvents404Error = (prisonNumber = 'G6115VJ'): SuperAgentRequest =>
  stubFor({
    request: {
      method: 'GET',
      urlPattern: `/match/${prisonNumber}/learner-events`,
    },
    response: {
      status: 404,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: {
        status: 404,
        developerMessage: `Learner Events for ${prisonNumber} not found`,
      },
    },
  })

const stubMatchLearnerEvents500Error = (prisonNumber = 'G6115VJ'): SuperAgentRequest =>
  stubFor({
    request: {
      method: 'GET',
      urlPattern: `/match/${prisonNumber}/learner-events`,
    },
    response: {
      status: 500,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: {
        status: 500,
        errorCode: null,
        userMessage: 'An unexpected error occurred',
        developerMessage: 'An unexpected error occurred',
        moreInfo: null,
      },
    },
  })

export default { stubMatchLearnerEvents, stubMatchLearnerEvents404Error, stubMatchLearnerEvents500Error }
