/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/action-plans/{prisonNumber}/goals': {
    post: operations['createGoal']
  }
  '/action-plans/{prisonNumber}': {
    get: operations['getActionPlan']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    CreateGoalRequest: {
      /**
       * @description A title explaining the aim of the goal.
       * @example Improve communication skills
       */
      title: string
      /**
       * @description A List of at least one Step.
       * @example null
       */
      steps: components['schemas']['CreateStepRequest'][]
      /**
       * @example null
       * @enum {string}
       */
      category?: 'WORK' | 'PERSONAL_DEVELOPMENT' | 'EDUCATION' | 'RESETTLEMENT'
      /**
       * @description Some additional notes related to the Goal.
       * @example Pay close attention to Peter's behaviour.
       */
      notes?: string
    }
    /**
     * @description A List of at least one Step.
     * @example null
     */
    CreateStepRequest: {
      /**
       * @description A title describing the step
       * @example Book first aid course
       */
      title: string
      /**
       * @description A target date range for the step to be completed by.
       * @example ZERO_TO_THREE_MONTHS
       */
      targetDateRange: string
      /**
       * Format: int32
       * @description The number (position) of the Step within the overall Goal.
       * @example 1
       */
      sequenceNumber: number
    }
    ActionPlanResponse: {
      /**
       * @description The ID of the prisoner
       * @example A1234BC
       */
      prisonNumber: string
      /**
       * @description A List of at least one or more Goals.
       * @example null
       */
      goals: components['schemas']['GoalResponse'][]
    }
    /**
     * @description A List of at least one or more Goals.
     * @example null
     */
    GoalResponse: {
      /**
       * @description The Goal's unique reference
       * @example c88a6c48-97e2-4c04-93b5-98619966447b
       */
      goalReference: string
      /**
       * @description A title explaining the aim of the goal.
       * @example Improve communication skills
       */
      title: string
      /**
       * @example null
       * @enum {string}
       */
      status: 'ACTIVE' | 'COMPLETED' | 'ARCHIVED'
      /**
       * @description A List of at least one Step.
       * @example null
       */
      steps: components['schemas']['StepResponse'][]
      /**
       * @description The name/ID of the person who created the goal. **Note that this is a placeholder for now currently not populated.**
       * @example TBD
       */
      createdBy: string
      /**
       * Format: date-time
       * @description An ISO-8601 timestamp representing when the Goal was created.
       * @example 2023-06-19T09:39:44Z
       */
      createdAt: string
      /**
       * @description The name/ID of the person who last updated the goal. **Note that this is a placeholder for now currently not populated.**
       * @example TBD
       */
      updatedBy: string
      /**
       * Format: date-time
       * @description An ISO-8601 timestamp representing when the Goal was last updated. This will be the same as the created date if it has not yet been updated.
       * @example 2023-06-19T09:39:44Z
       */
      updatedAt: string
      /**
       * @example null
       * @enum {string}
       */
      category?: 'WORK' | 'PERSONAL_DEVELOPMENT' | 'EDUCATION' | 'RESETTLEMENT'
      /**
       * @description Some additional notes related to the Goal.
       * @example Pay close attention to Peter's behaviour.
       */
      notes?: string
    }
    /**
     * @description A List of at least one Step.
     * @example null
     */
    StepResponse: {
      /**
       * @description A unique reference for the Step
       * @example d38a6c41-13d1-1d05-13c2-24619966119b
       */
      stepReference: string
      /**
       * @description A title describing the step
       * @example Book communication skills course
       */
      title: string
      /**
       * @description A target date range for the step to be completed by.
       * @example ZERO_TO_THREE_MONTHS
       */
      targetDateRange: string
      /**
       * @example null
       * @enum {string}
       */
      status: 'NOT_STARTED' | 'ACTIVE' | 'COMPLETE'
      /**
       * Format: int32
       * @description The number (position) of the Step within the overall Goal.
       * @example 1
       */
      sequenceNumber: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type external = Record<string, never>

export interface operations {
  createGoal: {
    parameters: {
      path: {
        prisonNumber: string
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateGoalRequest']
      }
    }
    responses: {
      /** @description Created */
      201: never
    }
  }
  getActionPlan: {
    parameters: {
      path: {
        prisonNumber: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['ActionPlanResponse']
        }
      }
    }
  }
}
