enum AbilityToWorkValue {
  LIMITED_BY_OFFENSE = 'LIMITED_BY_OFFENSE',
  CARING_RESPONSIBILITIES = 'CARING_RESPONSIBILITIES',
  HEALTH_ISSUES = 'HEALTH_ISSUES',
  NO_RIGHT_TO_WORK = 'NO_RIGHT_TO_WORK',
  OTHER = 'OTHER',
  NONE = 'NONE',
}

export default AbilityToWorkValue
