enum ActionPlanReviewCalculationRuleValue {
  PRISONER_READMISSION = 'PRISONER_READMISSION',
  PRISONER_TRANSFER = 'PRISONER_TRANSFER',
  BETWEEN_RELEASE_AND_3_MONTHS_TO_SERVE = 'BETWEEN_RELEASE_AND_3_MONTHS_TO_SERVE',
  BETWEEN_3_MONTHS_AND_3_MONTHS_7_DAYS_TO_SERVE = 'BETWEEN_3_MONTHS_AND_3_MONTHS_7_DAYS_TO_SERVE',
  BETWEEN_3_MONTHS_8_DAYS_AND_6_MONTHS_TO_SERVE = 'BETWEEN_3_MONTHS_8_DAYS_AND_6_MONTHS_TO_SERVE',
  BETWEEN_6_AND_12_MONTHS_TO_SERVE = 'BETWEEN_6_AND_12_MONTHS_TO_SERVE',
  BETWEEN_12_AND_60_MONTHS_TO_SERVE = 'BETWEEN_12_AND_60_MONTHS_TO_SERVE',
  MORE_THAN_60_MONTHS_TO_SERVE = 'MORE_THAN_60_MONTHS_TO_SERVE',
  INDETERMINATE_SENTENCE = 'INDETERMINATE_SENTENCE',
  PRISONER_ON_REMAND = 'PRISONER_ON_REMAND',
  PRISONER_UN_SENTENCED = 'PRISONER_UN_SENTENCED',
}

export default ActionPlanReviewCalculationRuleValue
