enum ApplicationAction {
  RECORD_INDUCTION = 'RECORD_INDUCTION',
  EXEMPT_INDUCTION = 'EXEMPT_INDUCTION',
  REMOVE_INDUCTION_EXEMPTION = 'REMOVE_INDUCTION_EXEMPTION',
  UPDATE_INDUCTION = 'UPDATE_INDUCTION',
  RECORD_EDUCATION = 'RECORD_EDUCATION',
  UPDATE_EDUCATION = 'UPDATE_EDUCATION',
  RECORD_REVIEW = 'RECORD_REVIEW',
  EXEMPT_REVIEW = 'EXEMPT_REVIEW',
  REMOVE_REVIEW_EXEMPTION = 'REMOVE_REVIEW_EXEMPTION',
  CREATE_GOALS = 'CREATE_GOALS',
  UPDATE_GOALS = 'UPDATE_GOALS',
  COMPLETE_AND_ARCHIVE_GOALS = 'COMPLETE_AND_ARCHIVE_GOALS',
  VIEW_SESSION_SUMMARIES = 'VIEW_SESSION_SUMMARIES',
  USE_DPS_LEARNER_RECORD_MATCHING_SERVICE = 'USE_DPS_LEARNER_RECORD_MATCHING_SERVICE',
}

export default ApplicationAction
