enum ApplicationRole {
  ROLE_LWP_MANAGER = 'ROLE_LWP_MANAGER',
  ROLE_LWP_CONTRIBUTOR = 'ROLE_LWP_CONTRIBUTOR',
  // ROLE_EDUCATION_WORK_PLAN_EDITOR is a deprecated role
  ROLE_EDUCATION_WORK_PLAN_EDITOR = 'ROLE_EDUCATION_WORK_PLAN_EDITOR',
}

export default ApplicationRole
