enum ChallengeIdentificationSource {
  EDUCATION_SKILLS_WORK = 'EDUCATION_SKILLS_WORK',
  WIDER_PRISON = 'WIDER_PRISON',
  CONVERSATIONS = 'CONVERSATIONS',
  COLLEAGUE_INFO = 'COLLEAGUE_INFO',
  FORMAL_PROCESSES = 'FORMAL_PROCESSES',
  SELF_DISCLOSURE = 'SELF_DISCLOSURE',
  OTHER_SCREENING_TOOL = 'OTHER_SCREENING_TOOL',
  OTHER = 'OTHER',
}

export default ChallengeIdentificationSource
