enum DpsRole {
  // LWP roles
  ROLE_LWP_MANAGER = 'ROLE_LWP_MANAGER',
  ROLE_LWP_CONTRIBUTOR = 'ROLE_LWP_CONTRIBUTOR',

  // LRS Matching Service roles
  ROLE_MATCH_LEARNER_RECORD_RW = 'ROLE_MATCH_LEARNER_RECORD_RW',
}

export default DpsRole
