enum EmployabilitySkillsValue {
  TEAMWORK = 'TEAMWORK',
  TIMEKEEPING = 'TIMEKEEPING',
  COMMUNICATION = 'COMMUNICATION',
  PLANNING = 'PLANNING',
  ORGANISATION = 'ORGANISATION',
  PROBLEM_SOLVING = 'PROBLEM_SOLVING',
  INITIATIVE = 'INITIATIVE',
  ADAPTABILITY = 'ADAPTABILITY',
  RELIABILITY = 'RELIABILITY',
  CREATIVITY = 'CREATIVITY',
}

export default EmployabilitySkillsValue
