enum InductionScheduleCalculationRuleValue {
  NEW_PRISON_ADMISSION = 'NEW_PRISON_ADMISSION',
  EXISTING_PRISONER_LESS_THAN_6_MONTHS_TO_SERVE = 'EXISTING_PRISONER_LESS_THAN_6_MONTHS_TO_SERVE',
  EXISTING_PRISONER_BETWEEN_6_AND_12_MONTHS_TO_SERVE = 'EXISTING_PRISONER_BETWEEN_6_AND_12_MONTHS_TO_SERVE',
  EXISTING_PRISONER_BETWEEN_12_AND_60_MONTHS_TO_SERVE = 'EXISTING_PRISONER_BETWEEN_12_AND_60_MONTHS_TO_SERVE',
  EXISTING_PRISONER_INDETERMINATE_SENTENCE = 'EXISTING_PRISONER_INDETERMINATE_SENTENCE',
  EXISTING_PRISONER_ON_REMAND = 'EXISTING_PRISONER_ON_REMAND',
  EXISTING_PRISONER_UN_SENTENCED = 'EXISTING_PRISONER_UN_SENTENCED',
}

export default InductionScheduleCalculationRuleValue
