enum InPrisonEducationValue {
  BARBERING_AND_HAIRDRESSING = 'BARBERING_AND_HAIRDRESSING',
  CATERING = 'CATERING',
  COMMUNICATION_SKILLS = 'COMMUNICATION_SKILLS',
  ENGLISH_LANGUAGE_SKILLS = 'ENGLISH_LANGUAGE_SKILLS',
  FORKLIFT_DRIVING = 'FORKLIFT_DRIVING',
  INTERVIEW_SKILLS = 'INTERVIEW_SKILLS',
  MACHINERY_TICKETS = 'MACHINERY_TICKETS',
  NUMERACY_SKILLS = 'NUMERACY_SKILLS',
  RUNNING_A_BUSINESS = 'RUNNING_A_BUSINESS',
  SOCIAL_AND_LIFE_SKILLS = 'SOCIAL_AND_LIFE_SKILLS',
  WELDING_AND_METALWORK = 'WELDING_AND_METALWORK',
  WOODWORK_AND_JOINERY = 'WOODWORK_AND_JOINERY',
  OTHER = 'OTHER',
}

export default InPrisonEducationValue
