enum ReasonToArchiveGoalValue {
  PRISONER_NO_LONGER_WANTS_TO_WORK_TOWARDS_GOAL = 'PRISONER_NO_LONGER_WANTS_TO_WORK_TOWARDS_GOAL',
  PRISONER_NO_LONGER_WANTS_TO_WORK_WITH_CIAG = 'PRISONER_NO_LONGER_WANTS_TO_WORK_WITH_CIAG',
  SUITABLE_ACTIVITIES_NOT_AVAILABLE_IN_THIS_PRISON = 'SUITABLE_ACTIVITIES_NOT_AVAILABLE_IN_THIS_PRISON',
  OTHER = 'OTHER',
}

export default ReasonToArchiveGoalValue
