enum ReasonToNotGetWorkValue {
  LIMIT_THEIR_ABILITY = 'LIMIT_THEIR_ABILITY',
  FULL_TIME_CARER = 'FULL_TIME_CARER',
  LACKS_CONFIDENCE_OR_MOTIVATION = 'LACKS_CONFIDENCE_OR_MOTIVATION',
  HEALTH = 'HEALTH',
  NO_REASON = 'NO_REASON',
  RETIRED = 'RETIRED',
  NO_RIGHT_TO_WORK = 'NO_RIGHT_TO_WORK',
  OTHER = 'OTHER',
  NOT_SURE = 'NOT_SURE',
}

export default ReasonToNotGetWorkValue
