enum SearchSortField {
  PRISONER_NAME = 'PRISONER_NAME',
  PRISON_NUMBER = 'PRISON_NUMBER',
  CELL_LOCATION = 'CELL_LOCATION',
  RELEASE_DATE = 'RELEASE_DATE',
  ENTERED_PRISON_DATE = 'ENTERED_PRISON_DATE',
  PLAN_STATUS = 'PLAN_STATUS',
}

export default SearchSortField
