enum SearchPlanStatus {
  PENDING_SCREENING_AND_ASSESSMENTS = 'PENDING_SCREENING_AND_ASSESSMENTS',
  ACTIVE_PLAN = 'ACTIVE_PLAN',
  NEEDS_PLAN = 'NEEDS_PLAN',
  EXEMPT = 'EXEMPT',
}

export default SearchPlanStatus
