---
# Per environment values which override defaults in hmpps-education-and-work-plan/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: learning-and-work-progress-preprod.hmpps.service.justice.gov.uk

  scheduledDowntime:
    enabled: true
    startup: '30 6 * * 1-5' # Start at 6.30am UTC Monday-Friday
    shutdown: '00 21 * * 1-5' # Stop at 9.00pm UTC Monday-Friday

  env:
    INGRESS_URL: "https://learning-and-work-progress-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    EDUCATION_AND_WORK_PLAN_API_URL: "https://learningandworkprogress-api-preprod.hmpps.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register-preprod.hmpps.service.justice.gov.uk"
    CURIOUS_API_URL: "https://preprodservices.sequation.net/sequation-virtual-campus2-api"
    DPS_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    NEW_DPS_URL: "https://dps-preprod.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-preprod.hmpps.service.justice.gov.uk"
    ACTIVITIES_API_URL: "https://activities-api-preprod.prison.service.justice.gov.uk"
    SUPPORT_ADDITIONAL_NEEDS_API_URL: 'https://support-for-additional-needs-api-preprod.hmpps.service.justice.gov.uk'
    SUPPORT_ADDITIONAL_NEEDS_UI_URL: "https://support-for-additional-needs-preprod.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: "PRE-PRODUCTION"

generic-prometheus-alerts:
  alertSeverity: hmpps-support-additional-needs-preprod
  businessHoursOnly: true
