---
# Per environment values which override defaults in hmpps-education-and-work-plan/values.yaml

generic-service:
  ingress:
    host: learning-and-work-progress.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://learning-and-work-progress.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    EDUCATION_AND_WORK_PLAN_API_URL: "https://learningandworkprogress-api.hmpps.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search.prison.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register.hmpps.service.justice.gov.uk"
    CURIOUS_API_URL: "https://liveservices.sequation.com/sequation-virtual-campus2-api"
    DPS_URL: "https://digital.prison.service.justice.gov.uk"
    NEW_DPS_URL: "https://dps.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components.hmpps.service.justice.gov.uk"
    ACTIVITIES_API_URL: "https://activities-api.prison.service.justice.gov.uk"
    SUPPORT_ADDITIONAL_NEEDS_API_URL: 'https://support-for-additional-needs-api.hmpps.service.justice.gov.uk'
    SUPPORT_ADDITIONAL_NEEDS_UI_URL: "https://support-for-additional-needs.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_TIMEOUT_RESPONSE: 10000
    HMPPS_AUTH_TIMEOUT_DEADLINE: 10000
    TOKEN_VERIFICATION_API_TIMEOUT_RESPONSE: 10000
    TOKEN_VERIFICATION_API_TIMEOUT_DEADLINE: 10000

generic-prometheus-alerts:
  alertSeverity: hmpps-support-additional-needs-prod
